import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'

import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/Components/Home/Header'
import StoreProvider from '../storeprovider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children, params: { locale } }) {
  const messages = await getMessages(locale)
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider messages={messages}>
          <StoreProvider>
            <Header />
            {children}
          </StoreProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
