import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'

import './globals.scss'
import StoreProvider from '../storeprovider'
import Header from '@/Components/Home/Navbar/Header'
import Hero from '@/Components/Home/Hero/Hero'

export const metadata = {
  title: 'SHOP.CO',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children, params: { locale } }) {
  const messages = await getMessages(locale)
  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
          <StoreProvider>
            <Header />
            {children}
          </StoreProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
