import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'
import Header from '@/Components/Home/Navbar/Header'
import StoreProvider from '../storeprovider'
import ClientWrapper from './ClientWrapper'
import './globals.scss'

export const metadata = {
  title: 'SHOP.CO',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children, params: { locale } }) {
  const messages = await getMessages(locale)

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
          <StoreProvider>
            <ClientWrapper>
              <Header />
              {children}
            </ClientWrapper>
          </StoreProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
